package greendao;

import java.util.List;
import com.guangda.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.guangda.dao.infoTypeDao;
import com.guangda.dao.infosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INFO_TYPE.
 */
public class infoType implements java.io.Serializable {

    private Long id;
    private String infoName;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient infoTypeDao myDao;

    private List<infos> infoes;

    public infoType() {
    }

    public infoType(Long id) {
        this.id = id;
    }

    public infoType(Long id, String infoName) {
        this.id = id;
        this.infoName = infoName;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getInfoTypeDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getInfoName() {
        return infoName;
    }

    public void setInfoName(String infoName) {
        this.infoName = infoName;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<infos> getInfoes() {
        if (infoes == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            infosDao targetDao = daoSession.getInfosDao();
            List<infos> infoesNew = targetDao._queryInfoType_Infoes(id);
            synchronized (this) {
                if(infoes == null) {
                    infoes = infoesNew;
                }
            }
        }
        return infoes;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetInfoes() {
        infoes = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
